import { db } from "../firebase.js";
import { doc, getDoc, setDoc, serverTimestamp } from "firebase/firestore";

/* =========================================================================
   EXPLORIA SPELLING BEE - THEMES & ACCURATE LOCAL VOCABULARY (ENGLISH)
   All images are locally stored in /images/spelling/<id>.jpg
   Themes are locally stored in /images/spelling/themes/<id>.jpg
   ========================================================================= */

export const SPELLING_THEMES = [
    {
        id: "all",
        title: "All Themes",
        emoji: "🌟",
        image: "/images/spelling/themes/all.jpg",
        description: "Mix of all topics",
    },
    {
        id: "animal",
        title: "Animals",
        emoji: "🦁",
        image: "/images/spelling/themes/animal.jpg?v=2",
        description: "Pets & wildlife",
    },
    {
        id: "food",
        title: "Food",
        emoji: "🍎",
        image: "/images/spelling/themes/food.jpg",
        description: "Fruits & snacks",
    },
    {
        id: "home",
        title: "Home",
        emoji: "🏠",
        image: "/images/spelling/themes/home.jpg",
        description: "Rooms & furniture",
    },
    {
        id: "body",
        title: "Body",
        emoji: "🧍",
        image: "/images/spelling/themes/body.jpg",
        description: "Body parts & senses",
    },
    {
        id: "subject",
        title: "Subjects",
        emoji: "📚",
        image: "/images/spelling/themes/subject.jpg?v=2",
        description: "School subjects",
    },
    {
        id: "music",
        title: "Music",
        emoji: "🎵",
        image: "/images/spelling/themes/music.jpg",
        description: "Instruments & sounds",
    },
    {
        id: "jobs",
        title: "Jobs",
        emoji: "👨‍⚕️",
        image: "/images/spelling/themes/jobs.jpg?v=2",
        description: "Careers & occupations",
    },
    {
        id: "clothes",
        title: "Clothes",
        emoji: "👕",
        image: "/images/spelling/themes/clothes.jpg",
        description: "Outfits & shoes",
    },
    {
        id: "sport",
        title: "Sports",
        emoji: "⚽",
        image: "/images/spelling/themes/sport.jpg",
        description: "Games & athletics",
    },
];

export const INITIAL_SPELLING_WORDS = [
    // -------------------------------------------------------------
    // 1. FOOD (10 words)
    // -------------------------------------------------------------
    {
        id: "banana",
        word: "banana",
        theme: "food",
        difficulty: "easy",
        image: "/images/spelling/banana.jpg",
        syllables: "ba • na • na",
        ipa: "/bəˈnæn.ə/",
        meaning: "A long curved yellow fruit with sweet soft flesh.",
        sentence: "The little monkey peeled a fresh [_______] to eat.",
        hintLetters: "B _ _ _ _ A (6 letters)",
    },
    {
        id: "apple",
        word: "apple",
        theme: "food",
        difficulty: "easy",
        image: "/images/spelling/apple.jpg",
        syllables: "ap • ple",
        ipa: "/ˈæp.əl/",
        meaning: "A round red or green crisp fruit that grows on trees.",
        sentence: "An [_______] a day keeps the doctor away.",
        hintLetters: "A _ _ _ E (5 letters)",
    },
    {
        id: "pizza",
        word: "pizza",
        theme: "food",
        difficulty: "easy",
        image: "/images/spelling/pizza.jpg",
        syllables: "piz • za",
        ipa: "/ˈpiːt.sə/",
        meaning: "A flat round baked bread base topped with tomato and melted cheese.",
        sentence: "We shared a warm slice of cheesy [_______] at dinner.",
        hintLetters: "P _ _ _ A (5 letters)",
    },
    {
        id: "burger",
        word: "burger",
        theme: "food",
        difficulty: "easy",
        image: "/images/spelling/burger.jpg",
        syllables: "bur • ger",
        ipa: "/ˈbɝː.ɡɚ/",
        meaning: "A round cooked patty placed inside a sliced bun.",
        sentence: "He ate a tasty beef [_______] served with french fries.",
        hintLetters: "B _ _ _ _ R (6 letters)",
    },
    {
        id: "orange",
        word: "orange",
        theme: "food",
        difficulty: "easy",
        image: "/images/spelling/orange.jpg",
        syllables: "or • ange",
        ipa: "/ˈɔːr.ɪndʒ/",
        meaning: "A round sweet citrus fruit with a bright orange skin.",
        sentence: "Fresh [_______] juice is packed with vitamin C.",
        hintLetters: "O _ _ _ _ E (6 letters)",
    },
    {
        id: "cheese",
        word: "cheese",
        theme: "food",
        difficulty: "medium",
        image: "/images/spelling/cheese.jpg",
        syllables: "cheese",
        ipa: "/tʃiːz/",
        meaning: "A dairy food made from pressed milk curds.",
        sentence: "The mouse nibbled a yellow piece of [_______].",
        hintLetters: "C _ _ _ _ E (6 letters)",
    },
    {
        id: "sandwich",
        word: "sandwich",
        theme: "food",
        difficulty: "medium",
        image: "/images/spelling/sandwich.jpg",
        syllables: "sand • wich",
        ipa: "/ˈsæn.wɪtʃ/",
        meaning: "Two slices of bread with fillings like egg or meat between them.",
        sentence: "I packed an egg and cheese [_______] for lunch.",
        hintLetters: "S _ _ _ _ _ _ H (8 letters)",
    },
    {
        id: "spaghetti",
        word: "spaghetti",
        theme: "food",
        difficulty: "hard",
        image: "/images/spelling/spaghetti.jpg",
        syllables: "spa • ghet • ti",
        ipa: "/spəˈɡet.i/",
        meaning: "Long, thin cylindrical Italian pasta noodles.",
        sentence: "We twirled our forks to eat the warm [_______] bolognese.",
        hintLetters: "S _ _ _ _ _ _ _ I (9 letters)",
    },
    {
        id: "chocolate",
        word: "chocolate",
        theme: "food",
        difficulty: "hard",
        image: "/images/spelling/chocolate.jpg",
        syllables: "choc • o • late",
        ipa: "/ˈtʃɑːk.lət/",
        meaning: "A sweet brown treat made from roasted cocoa seeds.",
        sentence: "She baked delicious cookies loaded with melted [_______].",
        hintLetters: "C _ _ _ _ _ _ _ E (9 letters)",
    },
    {
        id: "strawberry",
        word: "strawberry",
        theme: "food",
        difficulty: "hard",
        image: "/images/spelling/strawberry.jpg",
        syllables: "straw • ber • ry",
        ipa: "/ˈstrɔːˌber.i/",
        meaning: "A sweet red heart-shaped fruit with seeds on its surface.",
        sentence: "We dipped a ripe red [_______] into melted chocolate.",
        hintLetters: "S _ _ _ _ _ _ _ _ Y (11 letters)",
    },

    // -------------------------------------------------------------
    // 2. ANIMAL (10 words)
    // -------------------------------------------------------------
    {
        id: "lion",
        word: "lion",
        theme: "animal",
        difficulty: "easy",
        image: "/images/spelling/lion.jpg",
        syllables: "li • on",
        ipa: "/ˈlaɪ.ən/",
        meaning: "A majestic large tawny cat known as the king of the jungle.",
        sentence: "The mighty [_______] let out a powerful roar across the savanna.",
        hintLetters: "L _ _ N (4 letters)",
    },
    {
        id: "tiger",
        word: "tiger",
        theme: "animal",
        difficulty: "easy",
        image: "/images/spelling/tiger.jpg",
        syllables: "ti • ger",
        ipa: "/ˈtaɪ.ɡɚ/",
        meaning: "A large striped wild cat with orange and black fur.",
        sentence: "The striped [_______] prowled silently through the tall grass.",
        hintLetters: "T _ _ _ R (5 letters)",
    },
    {
        id: "rabbit",
        word: "rabbit",
        theme: "animal",
        difficulty: "easy",
        image: "/images/spelling/rabbit.jpg",
        syllables: "rab • bit",
        ipa: "/ˈræb.ɪt/",
        meaning: "A small furry mammal with long ears and a fluffy tail.",
        sentence: "The white [_______] hopped quickly into its underground burrow.",
        hintLetters: "R _ _ _ _ T (6 letters)",
    },
    {
        id: "monkey",
        word: "monkey",
        theme: "animal",
        difficulty: "easy",
        image: "/images/spelling/monkey.jpg",
        syllables: "mon • key",
        ipa: "/ˈmʌŋ.ki/",
        meaning: "A clever and playful animal that swings through trees.",
        sentence: "The cheeky [_______] snatched a fruit from the branch.",
        hintLetters: "M _ _ _ _ Y (6 letters)",
    },
    {
        id: "elephant",
        word: "elephant",
        theme: "animal",
        difficulty: "medium",
        image: "/images/spelling/elephant.jpg",
        syllables: "el • e • phant",
        ipa: "/ˈel.ə.fənt/",
        meaning: "The biggest land mammal with large ears and a long trunk.",
        sentence: "The giant [_______] sprayed cool water over its back with its trunk.",
        hintLetters: "E _ _ _ _ _ _ T (8 letters)",
    },
    {
        id: "dolphin",
        word: "dolphin",
        theme: "animal",
        difficulty: "medium",
        image: "/images/spelling/dolphin.jpg",
        syllables: "dol • phin",
        ipa: "/ˈdɑːl.fɪn/",
        meaning: "A smart and friendly ocean mammal that breathes air through a blowhole.",
        sentence: "A playful [_______] leaped gracefully above the ocean waves.",
        hintLetters: "D _ _ _ _ _ N (7 letters)",
    },
    {
        id: "giraffe",
        word: "giraffe",
        theme: "animal",
        difficulty: "medium",
        image: "/images/spelling/giraffe.jpg",
        syllables: "gi • raffe",
        ipa: "/dʒɪˈræf/",
        meaning: "The tallest living land animal, having a very long neck and spotted coat.",
        sentence: "The tall [_______] easily reached sweet leaves at the top of the tree.",
        hintLetters: "G _ _ _ _ _ E (7 letters)",
    },
    {
        id: "penguin",
        word: "penguin",
        theme: "animal",
        difficulty: "medium",
        image: "/images/spelling/penguin.jpg",
        syllables: "pen • guin",
        ipa: "/ˈpeŋ.ɡwɪn/",
        meaning: "A flightless black and white seabird that swims expertly in freezing water.",
        sentence: "The cute [_______] slid on its tummy across the icy snow.",
        hintLetters: "P _ _ _ _ _ N (7 letters)",
    },
    {
        id: "crocodile",
        word: "crocodile",
        theme: "animal",
        difficulty: "hard",
        image: "/images/spelling/crocodile.jpg",
        syllables: "croc • o • dile",
        ipa: "/ˈkrɑː.kə.daɪl/",
        meaning: "A large predatory aquatic reptile with thick armor and sharp teeth.",
        sentence: "A silent [_______] waited patiently beneath the river's surface.",
        hintLetters: "C _ _ _ _ _ _ _ E (9 letters)",
    },
    {
        id: "kangaroo",
        word: "kangaroo",
        theme: "animal",
        difficulty: "hard",
        image: "/images/spelling/kangaroo.jpg",
        syllables: "kan • ga • roo",
        ipa: "/ˌkæŋ.ɡəˈruː/",
        meaning: "An Australian animal that leaps on powerful legs and carries young in a pouch.",
        sentence: "The mother [_______] carried her tiny joey safely in her pouch.",
        hintLetters: "K _ _ _ _ _ _ O (8 letters)",
    },

    // -------------------------------------------------------------
    // 3. HOME (10 words)
    // -------------------------------------------------------------
    {
        id: "door",
        word: "door",
        theme: "home",
        difficulty: "easy",
        image: "/images/spelling/door.jpg",
        syllables: "door",
        ipa: "/dɔːr/",
        meaning: "A hinged barrier used to open and close the entrance of a room.",
        sentence: "Please knock gently on the wooden [_______] before entering.",
        hintLetters: "D _ _ R (4 letters)",
    },
    {
        id: "bed",
        word: "bed",
        theme: "home",
        difficulty: "easy",
        image: "/images/spelling/bed.jpg",
        syllables: "bed",
        ipa: "/bed/",
        meaning: "A piece of furniture with a mattress used for sleeping.",
        sentence: "He jumped into his cozy [_______] and fell soundly asleep.",
        hintLetters: "B _ D (3 letters)",
    },
    {
        id: "chair",
        word: "chair",
        theme: "home",
        difficulty: "easy",
        image: "/images/spelling/chair.jpg",
        syllables: "chair",
        ipa: "/tʃer/",
        meaning: "A separate seat for one person, typically with four legs and a back.",
        sentence: "Pull up a comfortable [_______] to sit at the desk.",
        hintLetters: "C _ _ _ R (5 letters)",
    },
    {
        id: "table",
        word: "table",
        theme: "home",
        difficulty: "easy",
        image: "/images/spelling/table.jpg",
        syllables: "ta • ble",
        ipa: "/ˈteɪ.bəl/",
        meaning: "A piece of furniture with a flat top and legs, used for dining or working.",
        sentence: "We placed the dinner plates neatly on the dining [_______].",
        hintLetters: "T _ _ _ E (5 letters)",
    },
    {
        id: "clock",
        word: "clock",
        theme: "home",
        difficulty: "easy",
        image: "/images/spelling/clock.jpg",
        syllables: "clock",
        ipa: "/klɑːk/",
        meaning: "A device that measures and displays the time.",
        sentence: "The wall [_______] chimed loudly when it struck seven o'clock.",
        hintLetters: "C _ _ _ K (5 letters)",
    },
    {
        id: "window",
        word: "window",
        theme: "home",
        difficulty: "medium",
        image: "/images/spelling/window.jpg",
        syllables: "win • dow",
        ipa: "/ˈwɪn.doʊ/",
        meaning: "An opening in a wall fitted with glass to let light and air inside.",
        sentence: "Open the bedroom [_______] to let the fresh morning breeze in.",
        hintLetters: "W _ _ _ _ W (6 letters)",
    },
    {
        id: "mirror",
        word: "mirror",
        theme: "home",
        difficulty: "medium",
        image: "/images/spelling/mirror.jpg",
        syllables: "mir • ror",
        ipa: "/ˈmɪr.ɚ/",
        meaning: "A polished reflective surface that shows the image of an object.",
        sentence: "She brushed her hair while looking into the bathroom [_______].",
        hintLetters: "M _ _ _ _ R (6 letters)",
    },
    {
        id: "kitchen",
        word: "kitchen",
        theme: "home",
        difficulty: "medium",
        image: "/images/spelling/kitchen.jpg",
        syllables: "kitch • en",
        ipa: "/ˈkɪtʃ.ən/",
        meaning: "A room equipped for cooking and preparing food.",
        sentence: "Dad is baking a warm apple pie inside the [_______].",
        hintLetters: "K _ _ _ _ _ N (7 letters)",
    },
    {
        id: "blanket",
        word: "blanket",
        theme: "home",
        difficulty: "medium",
        image: "/images/spelling/blanket.jpg",
        syllables: "blan • ket",
        ipa: "/ˈblæŋ.kɪt/",
        meaning: "A thick warm covering used on beds or when sitting on the sofa.",
        sentence: "I wrapped myself in a soft woolen [_______] to keep warm.",
        hintLetters: "B _ _ _ _ _ T (7 letters)",
    },
    {
        id: "refrigerator",
        word: "refrigerator",
        theme: "home",
        difficulty: "hard",
        image: "/images/spelling/refrigerator.jpg",
        syllables: "re • frig • er • a • tor",
        ipa: "/rɪˈfrɪdʒ.ə.reɪ.t̬ɚ/",
        meaning: "An appliance used for keeping food and beverages chilled and fresh.",
        sentence: "Put the carton of cold fresh milk back into the [_______].",
        hintLetters: "R _ _ _ _ _ _ _ _ _ _ R (12 letters)",
    },

    // -------------------------------------------------------------
    // 4. BODY (10 words)
    // -------------------------------------------------------------
    {
        id: "eye",
        word: "eye",
        theme: "body",
        difficulty: "easy",
        image: "/images/spelling/eye.jpg",
        syllables: "eye",
        ipa: "/aɪ/",
        meaning: "The body organ of sight and vision.",
        sentence: "She closed each [_______] to make a secret birthday wish.",
        hintLetters: "E _ E (3 letters)",
    },
    {
        id: "ear",
        word: "ear",
        theme: "body",
        difficulty: "easy",
        image: "/images/spelling/ear.jpg",
        syllables: "ear",
        ipa: "/ɪr/",
        meaning: "The body organ used for hearing sounds.",
        sentence: "Listen carefully with your left [_______] to hear the whisper.",
        hintLetters: "E _ R (3 letters)",
    },
    {
        id: "nose",
        word: "nose",
        theme: "body",
        difficulty: "easy",
        image: "/images/spelling/nose.jpg",
        syllables: "nose",
        ipa: "/noʊz/",
        meaning: "The part of the face that projects above the mouth, used for smelling.",
        sentence: "She smelled the sweet fragrance of flowers with her [_______].",
        hintLetters: "N _ _ E (4 letters)",
    },
    {
        id: "hand",
        word: "hand",
        theme: "body",
        difficulty: "easy",
        image: "/images/spelling/hand.jpg",
        syllables: "hand",
        ipa: "/hænd/",
        meaning: "The end part of the arm beyond the wrist, with fingers and thumb.",
        sentence: "Always wash every [_______] with soap before eating.",
        hintLetters: "H _ _ D (4 letters)",
    },
    {
        id: "mouth",
        word: "mouth",
        theme: "body",
        difficulty: "easy",
        image: "/images/spelling/mouth.jpg",
        syllables: "mouth",
        ipa: "/maʊθ/",
        meaning: "The facial opening through which humans speak, chew, and ingest food.",
        sentence: "He opened his [_______] wide at the dentist clinic.",
        hintLetters: "M _ _ _ H (5 letters)",
    },
    {
        id: "heart",
        word: "heart",
        theme: "body",
        difficulty: "medium",
        image: "/images/spelling/heart.jpg",
        syllables: "heart",
        ipa: "/hɑːrt/",
        meaning: "The muscular organ that pumps blood throughout your entire body.",
        sentence: "Your [_______] beats faster when you run and exercise.",
        hintLetters: "H _ _ _ T (5 letters)",
    },
    {
        id: "brain",
        word: "brain",
        theme: "body",
        difficulty: "medium",
        image: "/images/spelling/brain.jpg",
        syllables: "brain",
        ipa: "/breɪn/",
        meaning: "The organ of thought, memory, and nervous control inside the skull.",
        sentence: "Solving math riddles exercises your wonderful [_______].",
        hintLetters: "B _ _ _ N (5 letters)",
    },
    {
        id: "teeth",
        word: "teeth",
        theme: "body",
        difficulty: "medium",
        image: "/images/spelling/teeth.jpg",
        syllables: "teeth",
        ipa: "/tiːθ/",
        meaning: "Hard white enamel structures rooted in the jaws used for biting and chewing.",
        sentence: "Brush your shiny white [_______] every morning and evening.",
        hintLetters: "T _ _ _ H (5 letters)",
    },
    {
        id: "shoulder",
        word: "shoulder",
        theme: "body",
        difficulty: "hard",
        image: "/images/spelling/shoulder.jpg",
        syllables: "shoul • der",
        ipa: "/ˈʃoʊl.dɚ/",
        meaning: "The upper joint connecting human arms to the torso.",
        sentence: "He carried his school backpack over his right [_______].",
        hintLetters: "S _ _ _ _ _ R (8 letters)",
    },
    {
        id: "skeleton",
        word: "skeleton",
        theme: "body",
        difficulty: "hard",
        image: "/images/spelling/skeleton.jpg",
        syllables: "skel • e • ton",
        ipa: "/ˈskel.ə.t̬ən/",
        meaning: "The internal structural framework of bones supporting the human body.",
        sentence: "An adult human [_______] is made of 206 strong bones.",
        hintLetters: "S _ _ _ _ _ N (8 letters)",
    },

    // -------------------------------------------------------------
    // 5. SUBJECT (10 words)
    // -------------------------------------------------------------
    {
        id: "art",
        word: "art",
        theme: "subject",
        difficulty: "easy",
        image: "/images/spelling/art.jpg",
        syllables: "art",
        ipa: "/ɑːrt/",
        meaning: "The school subject of painting, drawing, and creative crafts.",
        sentence: "We used vibrant watercolors during our Friday [_______] class.",
        hintLetters: "A _ T (3 letters)",
    },
    {
        id: "music",
        word: "music",
        theme: "subject",
        difficulty: "easy",
        image: "/images/spelling/music.jpg",
        syllables: "mu • sic",
        ipa: "/ˈmjuː.zɪk/",
        meaning: "The study of tunes, singing, and playing musical instruments.",
        sentence: "The students learned rhythm and notes in [_______] class.",
        hintLetters: "M _ _ _ C (5 letters)",
    },
    {
        id: "maths",
        word: "maths",
        theme: "subject",
        difficulty: "easy",
        image: "/images/spelling/maths.jpg",
        syllables: "maths",
        ipa: "/mæθs/",
        meaning: "The school subject involving numbers, shapes, and calculations.",
        sentence: "We solved addition and multiplication problems in [_______].",
        hintLetters: "M _ _ _ S (5 letters)",
    },
    {
        id: "science",
        word: "science",
        theme: "subject",
        difficulty: "medium",
        image: "/images/spelling/science.jpg",
        syllables: "sci • ence",
        ipa: "/ˈsaɪ.əns/",
        meaning: "The study of nature, plants, gravity, and laboratory experiments.",
        sentence: "We mixed safe chemicals during an exciting [_______] experiment.",
        hintLetters: "S _ _ _ _ _ E (7 letters)",
    },
    {
        id: "english",
        word: "english",
        theme: "subject",
        difficulty: "medium",
        image: "/images/spelling/english.jpg",
        syllables: "eng • lish",
        ipa: "/ˈɪŋ.ɡlɪʃ/",
        meaning: "The study of grammar, literature, spelling, and reading comprehension.",
        sentence: "We wrote a creative adventure story for our [_______] homework.",
        hintLetters: "E _ _ _ _ _ H (7 letters)",
    },
    {
        id: "history",
        word: "history",
        theme: "subject",
        difficulty: "medium",
        image: "/images/spelling/history.jpg",
        syllables: "his • to • ry",
        ipa: "/ˈhɪs.tər.i/",
        meaning: "The study of ancient civilizations and past historical events.",
        sentence: "We explored ancient Egyptian pyramids in our [_______] lesson.",
        hintLetters: "H _ _ _ _ _ Y (7 letters)",
    },
    {
        id: "geography",
        word: "geography",
        theme: "subject",
        difficulty: "hard",
        image: "/images/spelling/geography.jpg",
        syllables: "ge • og • ra • phy",
        ipa: "/dʒiˈɑː.ɡrə.fi/",
        meaning: "The study of world maps, oceans, climates, and continents.",
        sentence: "We located every continent on the globe in [_______] class.",
        hintLetters: "G _ _ _ _ _ _ _ Y (9 letters)",
    },
    {
        id: "biology",
        word: "biology",
        theme: "subject",
        difficulty: "hard",
        image: "/images/spelling/biology.jpg",
        syllables: "bi • ol • o • gy",
        ipa: "/baɪˈɑː.lə.dʒi/",
        meaning: "The scientific study of all living organisms and life cycles.",
        sentence: "Under the microscope, we observed plant cells in [_______].",
        hintLetters: "B _ _ _ _ _ Y (7 letters)",
    },
    {
        id: "chemistry",
        word: "chemistry",
        theme: "subject",
        difficulty: "hard",
        image: "/images/spelling/chemistry.jpg",
        syllables: "chem • is • try",
        ipa: "/ˈkem.ə.stri/",
        meaning: "The science of matter, chemical elements, reactions, and bonds.",
        sentence: "Test tubes bubbled vigorously during our [_______] lab test.",
        hintLetters: "C _ _ _ _ _ _ _ Y (9 letters)",
    },
    {
        id: "physics",
        word: "physics",
        theme: "subject",
        difficulty: "hard",
        image: "/images/spelling/physics.jpg",
        syllables: "phys • ics",
        ipa: "/ˈfɪz.ɪks/",
        meaning: "The scientific study of matter, energy, light, and motion.",
        sentence: "We measured gravitational pull and speed in our [_______] class.",
        hintLetters: "P _ _ _ _ _ S (7 letters)",
    },

    // -------------------------------------------------------------
    // 6. MUSIC (10 words)
    // -------------------------------------------------------------
    {
        id: "drum",
        word: "drum",
        theme: "music",
        difficulty: "easy",
        image: "/images/spelling/drum.jpg",
        syllables: "drum",
        ipa: "/drʌm/",
        meaning: "A percussion instrument struck with wooden drumsticks or hands.",
        sentence: "He kept the energetic beat playing the bass [_______].",
        hintLetters: "D _ _ M (4 letters)",
    },
    {
        id: "piano",
        word: "piano",
        theme: "music",
        difficulty: "easy",
        image: "/images/spelling/piano.jpg",
        syllables: "pi • an • o",
        ipa: "/piˈæn.oʊ/",
        meaning: "A large musical instrument with a row of black and white keys.",
        sentence: "She played a melodious classical tune on the grand [_______].",
        hintLetters: "P _ _ _ O (5 letters)",
    },
    {
        id: "song",
        word: "song",
        theme: "music",
        difficulty: "easy",
        image: "/images/spelling/song.jpg",
        syllables: "song",
        ipa: "/sɔːŋ/",
        meaning: "A musical composition with sung lyrics.",
        sentence: "The classroom sang a happy chorus of the folk [_______].",
        hintLetters: "S _ _ G (4 letters)",
    },
    {
        id: "guitar",
        word: "guitar",
        theme: "music",
        difficulty: "medium",
        image: "/images/spelling/guitar.jpg",
        syllables: "gui • tar",
        ipa: "/ɡɪˈtɑːr/",
        meaning: "A musical instrument with six strings plucked with fingers or a pick.",
        sentence: "He strummed cheerful chords around the campfire on his [_______].",
        hintLetters: "G _ _ _ _ R (6 letters)",
    },
    {
        id: "flute",
        word: "flute",
        theme: "music",
        difficulty: "medium",
        image: "/images/spelling/flute.jpg",
        syllables: "flute",
        ipa: "/fluːt/",
        meaning: "A silver wind instrument held horizontally and blown across an opening.",
        sentence: "A gentle sweet melody floated from the silver [_______].",
        hintLetters: "F _ _ _ E (5 letters)",
    },
    {
        id: "violin",
        word: "violin",
        theme: "music",
        difficulty: "medium",
        image: "/images/spelling/violin.jpg",
        syllables: "vi • o • lin",
        ipa: "/ˌvaɪəˈlɪn/",
        meaning: "A small wooden four-stringed instrument played with a bow.",
        sentence: "The musician rested the wooden [_______] beneath her chin.",
        hintLetters: "V _ _ _ _ N (6 letters)",
    },
    {
        id: "trumpet",
        word: "trumpet",
        theme: "music",
        difficulty: "medium",
        image: "/images/spelling/trumpet.jpg",
        syllables: "trum • pet",
        ipa: "/ˈtrʌm.pɪt/",
        meaning: "A brass wind instrument with three valves and a flared horn.",
        sentence: "The brass band began the parade with a loud blast of the [_______].",
        hintLetters: "T _ _ _ _ _ T (7 letters)",
    },
    {
        id: "melody",
        word: "melody",
        theme: "music",
        difficulty: "hard",
        image: "/images/spelling/melody.jpg",
        syllables: "mel • o • dy",
        ipa: "/ˈmel.ə.di/",
        meaning: "A sequence of single musical notes that form a recognizable tune.",
        sentence: "The catchy lullaby [_______] helped the baby fall asleep.",
        hintLetters: "M _ _ _ _ Y (6 letters)",
    },
    {
        id: "rhythm",
        word: "rhythm",
        theme: "music",
        difficulty: "hard",
        image: "/images/spelling/rhythm.jpg",
        syllables: "rhy • thm",
        ipa: "/ˈrɪð.əm/",
        meaning: "A strong, regular, repeated tempo and pulse in music.",
        sentence: "The crowd clapped their hands in time to the upbeat [_______].",
        hintLetters: "R _ _ _ _ M (6 letters)",
    },
    {
        id: "orchestra",
        word: "orchestra",
        theme: "music",
        difficulty: "hard",
        image: "/images/spelling/orchestra.jpg",
        syllables: "or • ches • tra",
        ipa: "/ˈɔːr.kə.strə/",
        meaning: "A large ensemble of musicians playing string, woodwind, and brass instruments.",
        sentence: "The conductor stood on stage directing the symphony [_______].",
        hintLetters: "O _ _ _ _ _ _ _ A (9 letters)",
    },

    // -------------------------------------------------------------
    // 7. JOBS (10 words)
    // -------------------------------------------------------------
    {
        id: "chef",
        word: "chef",
        theme: "jobs",
        difficulty: "easy",
        image: "/images/spelling/chef.jpg",
        syllables: "chef",
        ipa: "/ʃef/",
        meaning: "A professional cook who prepares meals in a restaurant.",
        sentence: "The head [_______] wore a tall white hat while cooking in the kitchen.",
        hintLetters: "C _ _ F (4 letters)",
    },
    {
        id: "pilot",
        word: "pilot",
        theme: "jobs",
        difficulty: "easy",
        image: "/images/spelling/pilot.jpg",
        syllables: "pi • lot",
        ipa: "/ˈpaɪ.lət/",
        meaning: "A licensed person who flies aircraft and airplanes.",
        sentence: "The airline [_______] flew the plane smoothly above the clouds.",
        hintLetters: "P _ _ _ T (5 letters)",
    },
    {
        id: "nurse",
        word: "nurse",
        theme: "jobs",
        difficulty: "easy",
        image: "/images/spelling/nurse.jpg",
        syllables: "nurse",
        ipa: "/nɝːs/",
        meaning: "A medical worker who looks after sick and injured patients.",
        sentence: "The kind [_______] bandaged my scraped knee gently.",
        hintLetters: "N _ _ _ E (5 letters)",
    },
    {
        id: "farmer",
        word: "farmer",
        theme: "jobs",
        difficulty: "easy",
        image: "/images/spelling/farmer.jpg",
        syllables: "farm • er",
        ipa: "/ˈfɑːr.mɚ/",
        meaning: "A person who operates a farm, growing crops and caring for animals.",
        sentence: "The hardworking [_______] drove a tractor across the corn field.",
        hintLetters: "F _ _ _ _ R (6 letters)",
    },
    {
        id: "doctor",
        word: "doctor",
        theme: "jobs",
        difficulty: "medium",
        image: "/images/spelling/doctor.jpg",
        syllables: "doc • tor",
        ipa: "/ˈdɑːk.tɚ/",
        meaning: "A person licensed to practice medicine and heal patients.",
        sentence: "The hospital [_______] listened to my heartbeat with a stethoscope.",
        hintLetters: "D _ _ _ _ R (6 letters)",
    },
    {
        id: "teacher",
        word: "teacher",
        theme: "jobs",
        difficulty: "medium",
        image: "/images/spelling/teacher.jpg",
        syllables: "teach • er",
        ipa: "/ˈtiː.tʃɚ/",
        meaning: "A person who educates students in school classrooms.",
        sentence: "Our enthusiastic [_______] taught us all about the solar system.",
        hintLetters: "T _ _ _ _ _ R (7 letters)",
    },
    {
        id: "artist",
        word: "artist",
        theme: "jobs",
        difficulty: "medium",
        image: "/images/spelling/artist.jpg",
        syllables: "art • ist",
        ipa: "/ˈɑːr.tɪst/",
        meaning: "A person who paints, sketches, or creates works of fine art.",
        sentence: "The creative [_______] mixed oil colors on a wooden palette.",
        hintLetters: "A _ _ _ _ T (6 letters)",
    },
    {
        id: "police",
        word: "police",
        theme: "jobs",
        difficulty: "medium",
        image: "/images/spelling/police.jpg",
        syllables: "po • lice",
        ipa: "/pəˈliːs/",
        meaning: "Officers whose duty is to maintain public law, safety, and order.",
        sentence: "The patrol [_______] car stopped to assist traffic at the crossroads.",
        hintLetters: "P _ _ _ _ E (6 letters)",
    },
    {
        id: "astronaut",
        word: "astronaut",
        theme: "jobs",
        difficulty: "hard",
        image: "/images/spelling/astronaut.jpg",
        syllables: "as • tro • naut",
        ipa: "/ˈæs.trə.nɑːt/",
        meaning: "A person trained to travel and work in outer space.",
        sentence: "The brave [_______] floated in zero gravity outside the space station.",
        hintLetters: "A _ _ _ _ _ _ _ T (9 letters)",
    },
    {
        id: "firefighter",
        word: "firefighter",
        theme: "jobs",
        difficulty: "hard",
        image: "/images/spelling/firefighter.jpg",
        syllables: "fire • fight • er",
        ipa: "/ˈfaɪrˌfaɪ.t̬ɚ/",
        meaning: "A courageous rescuer trained to extinguish dangerous fires.",
        sentence: "The courageous [_______] climbed the high ladder with a fire hose.",
        hintLetters: "F _ _ _ _ _ _ _ _ _ R (11 letters)",
    },

    // -------------------------------------------------------------
    // 8. CLOTHES (10 words)
    // -------------------------------------------------------------
    {
        id: "hat",
        word: "hat",
        theme: "clothes",
        difficulty: "easy",
        image: "/images/spelling/hat.jpg",
        syllables: "hat",
        ipa: "/hæt/",
        meaning: "A head covering worn for warmth, shade, or fashion.",
        sentence: "He wore a wide straw [_______] to shield his eyes from the sun.",
        hintLetters: "H _ T (3 letters)",
    },
    {
        id: "shirt",
        word: "shirt",
        theme: "clothes",
        difficulty: "easy",
        image: "/images/spelling/shirt.jpg",
        syllables: "shirt",
        ipa: "/ʃɝːt/",
        meaning: "A garment for the upper body with a collar and buttons.",
        sentence: "He ironed his clean blue school [_______] neatly.",
        hintLetters: "S _ _ _ T (5 letters)",
    },
    {
        id: "shoes",
        word: "shoes",
        theme: "clothes",
        difficulty: "easy",
        image: "/images/spelling/shoes.jpg",
        syllables: "shoes",
        ipa: "/ʃuːz/",
        meaning: "Sturdy outer footwear protecting the feet.",
        sentence: "Tie your shoelaces tightly before putting on your [_______].",
        hintLetters: "S _ _ _ S (5 letters)",
    },
    {
        id: "socks",
        word: "socks",
        theme: "clothes",
        difficulty: "easy",
        image: "/images/spelling/socks.jpg",
        syllables: "socks",
        ipa: "/sɑːks/",
        meaning: "Soft knitted garments worn directly on feet inside shoes.",
        sentence: "He wore a pair of cozy striped [_______] on a chilly morning.",
        hintLetters: "S _ _ _ S (5 letters)",
    },
    {
        id: "pants",
        word: "pants",
        theme: "clothes",
        difficulty: "easy",
        image: "/images/spelling/pants.jpg",
        syllables: "pants",
        ipa: "/pænts/",
        meaning: "An outer garment covering the body from the waist to ankles.",
        sentence: "He wore comfortable denim [_______] for outdoor playing.",
        hintLetters: "P _ _ _ S (5 letters)",
    },
    {
        id: "dress",
        word: "dress",
        theme: "clothes",
        difficulty: "easy",
        image: "/images/spelling/dress.jpg",
        syllables: "dress",
        ipa: "/dres/",
        meaning: "A one-piece garment for women and girls consisting of a skirt and top.",
        sentence: "She wore an elegant yellow floral [_______] to the party.",
        hintLetters: "D _ _ _ S (5 letters)",
    },
    {
        id: "jacket",
        word: "jacket",
        theme: "clothes",
        difficulty: "medium",
        image: "/images/spelling/jacket.jpg",
        syllables: "jack • et",
        ipa: "/ˈdʒæk.ɪt/",
        meaning: "A warm outer garment opening down the front, with sleeves.",
        sentence: "Zip up your warm winter [_______] before stepping out in the snow.",
        hintLetters: "J _ _ _ _ T (6 letters)",
    },
    {
        id: "gloves",
        word: "gloves",
        theme: "clothes",
        difficulty: "medium",
        image: "/images/spelling/gloves.jpg",
        syllables: "gloves",
        ipa: "/ɡlʌvz/",
        meaning: "Coverings for the hands with individual sheaths for each finger.",
        sentence: "She slipped on thick woolen [_______] to build a snowman.",
        hintLetters: "G _ _ _ _ S (6 letters)",
    },
    {
        id: "boots",
        word: "boots",
        theme: "clothes",
        difficulty: "medium",
        image: "/images/spelling/boots.jpg",
        syllables: "boots",
        ipa: "/buːts/",
        meaning: "Sturdy footwear that covers the foot and extends up the ankle or leg.",
        sentence: "We wore yellow rain [_______] to splash happily in puddles.",
        hintLetters: "B _ _ _ S (5 letters)",
    },
    {
        id: "sweater",
        word: "sweater",
        theme: "clothes",
        difficulty: "hard",
        image: "/images/spelling/sweater.jpg",
        syllables: "sweat • er",
        ipa: "/ˈswet̬.ɚ/",
        meaning: "A knitted woolen garment worn over the torso for warmth.",
        sentence: "Grandma knitted a cozy red [_______] with festive snowflakes.",
        hintLetters: "S _ _ _ _ _ R (7 letters)",
    },

    // -------------------------------------------------------------
    // 9. SPORT (10 words)
    // -------------------------------------------------------------
    {
        id: "ball",
        word: "ball",
        theme: "sport",
        difficulty: "easy",
        image: "/images/spelling/ball.jpg",
        syllables: "ball",
        ipa: "/bɑːl/",
        meaning: "A spherical object used in numerous outdoor games and sports.",
        sentence: "He kicked the bouncy soccer [_______] right into the top corner.",
        hintLetters: "B _ _ L (4 letters)",
    },
    {
        id: "swim",
        word: "swim",
        theme: "sport",
        difficulty: "easy",
        image: "/images/spelling/swim.jpg",
        syllables: "swim",
        ipa: "/swɪm/",
        meaning: "Propel oneself through water using arms and kicking legs.",
        sentence: "We love to [_______] in the refreshing cool pool on hot afternoons.",
        hintLetters: "S _ _ M (4 letters)",
    },
    {
        id: "run",
        word: "run",
        theme: "sport",
        difficulty: "easy",
        image: "/images/spelling/run.jpg",
        syllables: "run",
        ipa: "/rʌn/",
        meaning: "Move swiftly on foot with speed faster than walking.",
        sentence: "Sprinters [_______] with maximum energy toward the finish tape.",
        hintLetters: "R _ N (3 letters)",
    },
    {
        id: "tennis",
        word: "tennis",
        theme: "sport",
        difficulty: "medium",
        image: "/images/spelling/tennis.jpg",
        syllables: "ten • nis",
        ipa: "/ˈten.ɪs/",
        meaning: "A racket sport where players strike a yellow felt ball across a net.",
        sentence: "She hit a fast ace during the championship [_______] match.",
        hintLetters: "T _ _ _ _ S (6 letters)",
    },
    {
        id: "soccer",
        word: "soccer",
        theme: "sport",
        difficulty: "medium",
        image: "/images/spelling/soccer.jpg",
        syllables: "soc • cer",
        ipa: "/ˈsɑː.kɚ/",
        meaning: "A football game played by eleven players kicking a ball into a goal.",
        sentence: "He scored a thrilling goal in the final minutes of the [_______] game.",
        hintLetters: "S _ _ _ _ R (6 letters)",
    },
    {
        id: "boxing",
        word: "boxing",
        theme: "sport",
        difficulty: "medium",
        image: "/images/spelling/boxing.jpg",
        syllables: "box • ing",
        ipa: "/ˈbɑːk.sɪŋ/",
        meaning: "A combat sport where athletes wear padded gloves inside a ring.",
        sentence: "He practiced punches and footwork in the [_______] gym.",
        hintLetters: "B _ _ _ _ G (6 letters)",
    },
    {
        id: "cycling",
        word: "cycling",
        theme: "sport",
        difficulty: "medium",
        image: "/images/spelling/cycling.jpg",
        syllables: "cy • cling",
        ipa: "/ˈsaɪ.klɪŋ/",
        meaning: "The sport or activity of riding a bicycle.",
        sentence: "We went [_______] along the scenic lakeside trail together.",
        hintLetters: "C _ _ _ _ _ G (7 letters)",
    },
    {
        id: "basketball",
        word: "basketball",
        theme: "sport",
        difficulty: "hard",
        image: "/images/spelling/basketball.jpg",
        syllables: "bas • ket • ball",
        ipa: "/ˈbæs.kət.bɑːl/",
        meaning: "A game where two teams score by tossing a ball through an elevated hoop.",
        sentence: "The player jumped high and threw the [_______] into the hoop.",
        hintLetters: "B _ _ _ _ _ _ _ _ L (10 letters)",
    },
    {
        id: "badminton",
        word: "badminton",
        theme: "sport",
        difficulty: "hard",
        image: "/images/spelling/badminton.jpg",
        syllables: "bad • min • ton",
        ipa: "/ˈbæd.mɪn.tən/",
        meaning: "A court sport played by hitting a feathered shuttlecock across a high net.",
        sentence: "He smashed the shuttlecock powerfully during the [_______] finals.",
        hintLetters: "B _ _ _ _ _ _ _ N (9 letters)",
    },
    {
        id: "gymnastics",
        word: "gymnastics",
        theme: "sport",
        difficulty: "hard",
        image: "/images/spelling/gymnastics.jpg",
        syllables: "gym • nas • tics",
        ipa: "/dʒɪmˈnæs.tɪks/",
        meaning: "A sport showcasing physical flexibility, balance, flips, and agility.",
        sentence: "The gymnast stuck a flawless balance landing in [_______].",
        hintLetters: "G _ _ _ _ _ _ _ _ S (10 letters)",
    },
];

/**
 * Normalizes difficulty value ("easy" | "medium" | "hard")
 */
export function normalizeDifficulty(diff) {
    if (diff === 1 || diff === "1" || diff === "easy") return "easy";
    if (diff === 2 || diff === "2" || diff === "medium") return "medium";
    if (diff === 3 || diff === "3" || diff === "hard") return "hard";
    return "easy";
}

/**
 * 1. Muat senarai perkataan Spelling Bee (Firestore -> LocalStorage -> Default)
 */
export async function getSpellingWords() {
    let localData = null;
    if (typeof window !== "undefined") {
        try {
            // Invalidate older cache versions that had incorrect images
            const rawV3 = localStorage.getItem("exploria_spelling_words_v3");
            if (rawV3) {
                const parsed = JSON.parse(rawV3);
                if (Array.isArray(parsed) && parsed.length > 0) {
                    localData = parsed;
                }
            } else {
                // Clear obsolete v1/v2 caches so user gets accurate local pictures immediately
                localStorage.removeItem("exploria_spelling_words");
                localStorage.removeItem("exploria_spelling_words_v2");
            }
        } catch (e) {
            console.warn("Error reading local spelling words:", e);
        }
    }

    try {
        const docRef = doc(db, "kurikulum", "spelling_bee_v3");
        const docSnap = await getDoc(docRef);

        if (docSnap.exists() && Array.isArray(docSnap.data().words) && docSnap.data().words.length > 0) {
            const words = docSnap.data().words;
            if (typeof window !== "undefined") {
                try {
                    localStorage.setItem("exploria_spelling_words_v3", JSON.stringify(words));
                } catch {}
            }
            return words;
        }
    } catch (err) {
        console.warn("⚠️ [Spelling] Using local or fallback vocabulary:", err.message);
    }

    return localData || INITIAL_SPELLING_WORDS;
}

/**
 * 2. Simpan keseluruhan senarai perkataan ke Firestore & LocalStorage
 */
export async function saveSpellingWords(words) {
    if (!Array.isArray(words)) return { success: false, error: "Invalid word list format." };

    if (typeof window !== "undefined") {
        try {
            localStorage.setItem("exploria_spelling_words_v3", JSON.stringify(words));
            window.dispatchEvent(new Event("exploria_spelling_updated"));
        } catch {}
    }

    try {
        const docRef = doc(db, "kurikulum", "spelling_bee_v3");
        await setDoc(docRef, {
            words,
            dikemaskiniPada: serverTimestamp(),
        }, { merge: true });
        return { success: true };
    } catch (err) {
        console.error("Error saving words to Firestore:", err);
        return { success: true, localOnly: true };
    }
}
